version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: demo
      POSTGRES_DB: demo_db
    volumes:
      - ~/docker/rails-demo/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
