version: '3.7'

services:
  app:
    build:
      context: .
    depends_on:
      - db

  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: demo
      POSTGRES_DB: demo_db
