version: '3.7'

services:
  app:
    build:
      context: .
      cache_from:
        - alexrozhnov/rails_demo:latest
    image: alexrozhnov/rails_demo:latest
    environment:
      RAILS_ENV: test
    depends_on:
      - db

  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: demo
      POSTGRES_DB: demo_db_test
