# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build app
        run: |
          docker-compose -f docker-compose.test.yaml pull app
          docker-compose -f docker-compose.test.yaml build          

      # Runs a single command using the runners shell
      - name: Run test
        run: docker-compose -f docker-compose.test.yaml run --rm app rails test

      - name: Push image
        run: docker-compose -f docker-compose.test.yaml push app

      # Runs a set of commands using the runners shell
      - name: Stop services
        run: docker-compose down
        if: ${{ always() }}
